# Install tpm if it not already installed
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"


# Vi keys for visual mode, maybe more stuff also
set -g mode-keys vi
set -g mouse on
set -g default-terminal "tmux-256color"

# Vi keys for pane movement
bind h select-pane -L
bind j select-pane -U
bind k select-pane -D
bind l select-pane -R

# Go to link or open file under cursor  with open, this one needs some more work
bind -T copy-mode-vi x send-keys -X copy-pipe-and-cancel "xargs open"

# Should make some kind of comment here
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# rose-pine theme
set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'main'

# tmux-window-name installed with pipx [uninstalled due to security: use of eval in python scripts]
# set-hook -g after-new-window 'run-shell "tmux-window-name"'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'

 # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
 run '~/.tmux/plugins/tpm/tpm'

