# Vi keys for visual mode, maybe more stuff also
set -g mode-keys vi
set -g mouse on
set -g default-terminal "tmux-256color"

# Vi keys for pane movement
bind h select-pane -L
bind j select-pane -U
bind k select-pane -D
bind l select-pane -R

# Go to link or open file under cursor  with open, this one needs some more work
bind -T copy-mode-vi x send-keys -X copy-pipe-and-cancel "xargs open"

# Should make some kind of comment here
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel


