# Install tpm if it not already installed
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"


# Vi keys for visual mode, maybe more stuff also
set -g mode-keys vi
set -g mouse on
set -g default-terminal "tmux-256color"

# Vi keys for pane movement
bind h select-pane -L
bind j select-pane -U
bind k select-pane -D
bind l select-pane -R

bind H swap-pane -d -t '{left-of}'
bind J swap-pane -d -t '{down-of}'
bind K swap-pane -d -t '{up-of}'
bind L swap-pane -d -t '{right-of}'

# Go to link or open file under cursor  with open, this one needs some more work
bind -T copy-mode-vi x send-keys -X copy-pipe-and-cancel "xargs open"

# Should make some kind of comment here
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'MunifTanjim/tmux-mode-indicator'

# rose-pine theme
set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_show_current_program 'on'
set -g @rose_pine_show_pane_directory 'on'

set -g @rose_pine_variant 'main'

#TODO: Look into if there is another good tmux window renamer
# tmux-window-name installed with pipx [uninstalled due to security: use of eval in python scripts]
# These settings will instead be handled by rose-pine
# set-hook -g after-new-window 'run-shell "tmux-window-name"'
# set -g automatic-rename off

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
# These are not padded
set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
set -g @rose_pine_current_window_icon '' # Changes the default icon to the left of the active window name
set -g @rose_pine_folder_icon '' # Changes the default icon to the left of the current directory folder
set -g @rose_pine_username_icon '' # Changes the default icon to the right of the hostname
set -g @rose_pine_hostname_icon '󰒋' # Changes the default icon to the right of the hostname
set -g @rose_pine_date_time_icon '󰃰' # Changes the default icon to the right of the date module

# set -g @rose_pine_left_prepend_section '#{tmux_mode_indicator}'

 # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
 run '~/.tmux/plugins/tpm/tpm'

